FROM ubuntu:trusty

RUN apt-get update && apt-get install -yq curl && apt-get clean

WORKDIR /Users/hawk/dockerlab/hello_world

ADD test.sh /Users/hawk/dockerlab/hello_world/test.sh

CMD ["bash", "test.sh"]
